# Use R language
language: r

# Define multiple R-versions, one from bioconductor
#r:
#  - oldrel
#  - release
#  - devel
#  - bioc-devel

# Set one of you dependencies from github
#r_github_packages: r-lib/testthat

# Set one of your dependencies from CRAN
#r_packages: RTest

# Set a Linux system dependency
#apt_packages:
#  - libxml2-dev
